export default {
  translation: {
    app_title: "Qandel Blbas Co.",
    home1: "For General Trading & Steel Products",
    home2: "For General Trading & Steel Products",
    home3: "For General Trading & Steel Products",
    home: "Home",
    about: "About",
    services: "Services",
    partners: "Partners",
    sanaPanel: "Sana Panel",
    powerPanel: "Power Panel",
    power: "Power",
    blackPipe: "Black Pipe",
    products: "Our Products",
    contact: "Contact",
    about_us: "About Us",
    about_p: `Qandel Blbas Company. Founded in 2010, Qandel Blbas is a
        local company operating in the fields of importing steel
        and its different products and the production of Sandwich
        Panels and distributing them across all the provinces of
        the country. Qandel Blbas aims to import the products that
        will positively contribute to reconstruction of the
        country and establishing economic infrastructure. Our
        imports, produced in factories abroad, confirm to Iraqi
        and international standards, and we import them on demand
        and to fill the needs of the domestic market. We try to
        develop domestic industrial production and for all
        production become local. To that end, we have established
        production of Sandwich panel in the city of Zakho, and for
        the future, we plan to establish a factory producing pipes
        and profils in Erbil.`,
    why_chose_us: "Why Choose Us ?",
    reason1: "Safety",
    contact_form: "Contact Form",
    name: "Name",
    email: "E-mail",
    message: "Message",
    send_message: "Send Message",
    contact_p:
      "An Iraqi delivery company. Our goal is to give the best model for delivery companies by employing expertise and using the latest internationally approved technology.",
    address: "Address",
    address_value:
      "Runaki St., opposite of the WestEye hospital, Said Taib Baqal building 7th floor, Irbil, Iraq",
    phone: "Phone",
    copy_right: "© All Rights Reserved Qandel blbas Co.",
    page_not_found: "Page Not Found",
    is_required: "is required!",
    not_valid: "is not a valid email!",
    service1: "cutting in length",
    service1_p:
      "To cut rolls and turn them into waiters (ties) according to requests, and for all types of galvanized iron, colored, cold black roll, hot black roll.",
    service1_li1: "Roll width: from 40 cm to 150 cm",
    service1_li2: "Roll thickness: 0.20 mm to 2.00 mm",
    service1_li3: "Cutting length: from 125 cm to 700 cm",
    service2: "Making corrugated steel sheets",
    service2_p:
      "To produce kirby panels (roof gables) for the roofs of buildings, warehouses and yards.",
    service2_li1: "Roller width used: 120cm, 122cm, 125cm.",
    service2_li2: "Product Width: 100cm (Net).",
    service2_li3: "Plate thickness: 0.20 to 0.90 mm",
    service2_li4: "The length of the kirby: from 125 cm to 1700 cm",

    s_top_header1: "Sana Panel Manufacturer of sandwich panels",
    s_about_p:
      "Sana panel is a local factory established in 2017 .The factory started to produce sandwich panel for both roof and wall in 2018. The production of this factory is with automated machine and high quality with standard requirements and costumer demands meet. The aim of the company is to develop and reconstruct the country with a local product and provide more job opportunities.",
    s_whatspanel: "Whats Sandwich Panel",
    s_whatspanel_p:
      "Actually sandwich panel is three ply light compound structure, Shows extraordinary performances and advantages. A sandwich panel compound, in comparison with its components has much more resistance and also can be used qqickly and easily in constructions. In this modern construction material, insulation polyurethane foam or layers wwith specific physical features such as defined density and fire resitance calss, placed between external and internal layers. These three components are inseparable, and function as integrated object. Whereas are very good heat and cold insulation, using them cause energy costs significantly reduce.",
    s_availables: "Available Dimentions & Thikness",
    s_specifics: "Specifications",
    s_spec_width: "Width",
    s_spec_length: "Length",
    s_spec_thikness: "Thikness",
    s_spec_density: "Density",
    s_spec_thermal: "Thermal Conductivity",
    s_spec_sound: "Sound Isolation",
    s_roof: "Roof Panel",
    s_wall: "Wall Panel",
    s_f_1: "1000 mm",
    s_f_2: "18 m max",
    s_f_3: "50, 75, 100 mm",
    s_f_4: "40 kg/m",
    s_f_4a: " (∓2)",
    s_f_5: "0.022 w/mk",
    s_f_6: "25 dB",
    s_application: "Application",
    s_application_p:
      "Sandwich panel can be widly used in the construction of factories, showrooms, offices, restaurant, theaters, schools, malls, ssupermarkets, warehouses, poultry halls, ssport clubs, airport, terminals, etc",
    s_type: "Product Types",
    s_type1: "Sandwich Panel Rigid Polyurethane (PUR)",
    s_type2: "Sandwich Panel Polyisocyanurate (PIR)",
    s_type3: "Sandwich Panel Ridges",
    s_specification: "Specifications",
    s_specific_1: "Rain and vapor resistance",
    s_specific_2: "Rusting reesistance",
    s_specific_3: "Wind resistance",
    s_specific_4: "Sun light resistance",
    s_specific_5: " Chemical resistance",
    s_specific_6: " Fire resistance",
    s_specific_7: "Heat insulation",
    s_specific_8: "Sound insulation",
    s_specific_9: "Thrust and earthquake resistance",
    s_specific_10: "Insects resistance",
    s_specific_11: "Nice apperance",
    s_specific_12: "Protective against pollutions",
    s_specific_13: "Cost effective",
    s_specific_14: "Variable colors",
    s_specific_15: "High durability",
    s_specific_16: "Recyclable",
    s_add_value: "duhok, zhaxo, Hasan Ava, Behind the car showroom",
    p_top_header1: "Power Panel Manufacturer of sandwich panels",
    p_about_p:
      "power panel is a local factory established in 2017 .The factory started to produce sandwich panel for both roof and wall in 2018. The production of this factory is with automated machine and high quality with standard requirements and costumer demands meet. The aim of the company is to develop and reconstruct the country with a local product and provide more job opportunities.",
    p_whatspanel: "Whats Sandwich Panel",
    p_whatspanel_p:
      "Actually sandwich panel is three ply light compound structure, Shows extraordinary performances and advantages. A sandwich panel compound, in comparison with its components has much more resistance and also can be used qqickly and easily in constructions. In this modern construction material, insulation polyurethane foam or layers wwith specific physical features such as defined density and fire resitance calss, placed between external and internal layers. These three components are inseparable, and function as integrated object. Whereas are very good heat and cold insulation, using them cause energy costs significantly reduce.",
    p_availables: "Available Dimentions & Thikness",
    p_specifics: "Specifications",
    p_spec_width: "Width",
    p_spec_length: "Length",
    p_spec_thikness: "Thikness",
    p_spec_density: "Density",
    p_spec_thermal: "Thermal Conductivity",
    p_spec_sound: "Sound Isolation",
    p_roof: "Roof Panel",
    p_wall: "Wall Panel",
    p_f_1: "1000 mm",
    p_f_2: "18 m max",
    p_f_3: "50, 75, 100 mm",
    p_f_4: "40 kg/m",
    p_f_4a: " (∓2)",
    p_f_5: "0.022 w/mk",
    p_f_6: "25 dB",
    p_application: "Application",
    p_application_p:
      "Sandwich panel can be widly used in the construction of factories, showrooms, offices, restaurant, theaters, schools, malls, ssupermarkets, warehouses, poultry halls, ssport clubs, airport, terminals, etc",
    p_type: "Product Types",
    p_type1: "Sandwich Panel Rigid Polyurethane (PUR)",
    p_type2: "Sandwich Panel Polyisocyanurate (PIR)",
    p_type3: "Sandwich Panel Ridges",
    p_specification: "Specifications",
    p_specific_1: "Rain and vapor resistance",
    p_specific_2: "Rusting reesistance",
    p_specific_3: "Wind resistance",
    p_specific_4: "Sun light resistance",
    p_specific_5: " Chemical resistance",
    p_specific_6: " Fire resistance",
    p_specific_7: "Heat insulation",
    p_specific_8: "Sound insulation",
    p_specific_9: "Thrust and earthquake resistance",
    p_specific_10: "Insects resistance",
    p_specific_11: "Nice apperance",
    p_specific_12: "Protective against pollutions",
    p_specific_13: "Cost effective",
    p_specific_14: "Variable colors",
    p_specific_15: "High durability",
    p_specific_16: "Recyclable",
    p_add_value: "duhok, zhaxo, Hasan Ava, Behind the car showroom",
  },
};
